### PR TITLE
add poetry support

### PR DESCRIPTION
**Pull request by lucasiscovici2**

### CODE REVIEW

**Comment by abduhbm** [comment]
Thanks @lucasiscovici2,
Can you please add a test for this?

**Review by abduhbm — CHANGES_REQUESTED** [review]
Thanks @lucasiscovici2 
Can you please add a test for this?

**Comment by lucasiscovici2** [comment]
> Thanks @lucasiscovici2 Can you please add a test for this?

HEllo, it's ok :)

**Review by abduhbm — APPROVED** [review]

**Comment by abduhbm** [comment]
Thanks a lot @lucasiscovici2

**Pull request merged**
